#! /bin/sh

if [ `whoami` != "root" ]; then
    printf "Please run this script as root\n"
    exit 1
fi

tee /sys/bus/pci/devices/0000\:01\:00\.1/remove <<< 1
tee /sys/bus/pci/devices/0000\:01\:00\.0/remove <<< 1

